# Generated by Django 2.1.15 on 2020-06-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
